#ifndef LIBUARTCONFIG_H_
#define LIBUARTCONFIG_H_
#include "sys/AT91SAM7S64.h"
#include "sys/lib_AT91SAM7S64.h"

#define kLIBUART_INPUT_BUFFER_SIZE 128

#define mDISABLE_UART_RX_IT() AT91F_US_DisableIt(AT91C_BASE_US0,AT91C_US_RXRDY)
#define mENABLE_UART_RX_IT() AT91F_US_EnableIt(AT91C_BASE_US0,AT91C_US_RXRDY)
#define mSEND_BUFF(PTR , LEN) AT91F_US_SendFrame(AT91C_BASE_US0,(char *)PTR,LEN,0,0)
#endif /*LIBUARTCONFIG_H_*/
