#ifndef LIBTIMERCONFIG_H_
#define LIBTIMERCONFIG_H_

#include "sys/AT91SAM7S64.h"
#include "sys/lib_AT91SAM7S64.h" 
#define LIBTIMER_MAX_TIMER_NUMBER 15
#define kLIBTIMER_ENABLE_IT()  AT91F_PITEnableInt(AT91C_BASE_PITC);
#define kLIBTIMER_DISABLE_IT() AT91F_PITDisableInt(AT91C_BASE_PITC);

#endif /*LIBTIMERCONFIG_H_*/
